# Generated by Django 4.0.4 on 2022-04-11 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebAuthnCredential",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("id", models.BinaryField(primary_key=True, serialize=False)),
                ("public_key", models.BinaryField()),
                ("sign_count", models.IntegerField()),
                ("transports", models.CharField(max_length=32)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="webauthncredential",
            index=models.Index(fields=["id"], name="credential_id_idx"),
        ),
        migrations.AddIndex(
            model_name="webauthncredential",
            index=models.Index(fields=["user"], name="credential_user_idx"),
        ),
        migrations.AddConstraint(
            model_name="webauthncredential",
            constraint=models.UniqueConstraint(
                fields=("id", "user"), name="unique_credential_user"
            ),
        ),
    ]
