# Generated by Django 4.0.4 on 2022-05-06 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebAuthnCredential',
        ),
    ]
